In [23]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series
import statistics

In [24]:
#2.15w
NBA=pd.read_excel('NBACost2013.xlsx')

In [25]:
NBA.sort_values(by='Cost($)',inplace=True)

In [26]:
def f(data):
    return DataFrame({"Relative Frequency": (data['Cost($)'])/(NBA['Cost($)'].sum()),
                      "Percentage Distribution":(data['Cost($)'])/(NBA['Cost($)'].sum())*100
                     })
Distribution=f(NBA)

In [27]:
pd.merge(NBA,Distribution,left_index=True,right_index=True)

,Team Name,Cost($),Relative Frequency,Percentage Distribution
3,Charlotte Bobcats,203.06,0.020746,2.074598
18,New Orleans Pelicans,208.48,0.021300,2.129972
14,Memphis Grizzlies,212.16,0.021676,2.167570
11,Indiana Pacers,227.36,0.023229,2.322863
0,Atlanta Hawks,240.04,0.024524,2.452411
29,Washington Wizards,249.22,0.025462,2.546200
8,Detroit Pistons,262.40,0.026809,2.680856
21,Orlando Magic,263.10,0.026880,2.688007
22,Philadelphia 76ers,266.40,0.027217,2.721722
25,Sacramento Kings,268.28,0.027409,2.740930
5,Cleveland Cavaliers,271.74,0.027763,2.776279
17,Minnesota Timberwolves,273.98,0.027992,2.799165
28,Utah Jazz,280.98,0.028707,2.870681
20,Oklahoma City Thunder,295.40,0.030180,3.018006
24,Portland Trail Blazers,308.18,0.031486,3.148575
16,Milwaukee Bucks,309.30,0.031600,3.160018
7,Denver Nuggets,319.10,0.032601,3.260141
6,Dallas Mavericks,321.18,0.032814,3.281392
27,Toronto Raptors,321.63,0.032860,3.285989
9,Golden State Warriors,324.08,0.033110,3.311020
10,Houston Rockets,336.05,0.034333,3.433314
26,San Antonio Spurs,338.00,0.034532,3.453236
23,Phoenix Suns,344.92,0.035239,3.523936
2,Brooklyn Nets,382.00,0.039028,3.902770
12,Los Angeles Clippers,395.20,0.040376,4.037630
1,Boston Celtics,434.96,0.044438,4.443845
4,Chicago Bulls,456.60,0.046649,4.664934
15,Miami Heat,472.20,0.048243,4.824314
13,Los Angeles Lakers,542.00,0.055374,5.537438
19,New York Knicks,659.92,0.067422,6.742188

In [28]:
NBA.shape

(30, 2)

In [31]:
IntervalWidth=(NBA['Cost($)'].max()-NBA['Cost($)'].min())/50
IntervalWidth

9.1372

In [35]:
#2.16
utility=pd.read_excel("utility.xlsx")
utility.shape

(50, 1)

In [36]:
utility.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 1 columns):
Utility Charge    50 non-null int64
dtypes: int64(1)
memory usage: 480.0 bytes

In [65]:
def f(x):
    
    return DataFrame({"Relative Frequency":(x['Utility Charge'])/(x['Utility Charge'].sum()),
                      "Percentage Distribution":(x['Utility Charge'])/(x['Utility Charge'].sum())*100,
                      'Cumulative Distribution':((x['Utility Charge'])/(x['Utility Charge'].sum())*100).cumsum()
                     })
dist=f(utility)

In [66]:
pd.merge(utility,dist,left_index=True,right_index=True)

,Utility Charge,Relative Frequency,Percentage Distribution,Cumulative Distribution
0,96,0.013056,1.305590,1.305590
1,171,0.023256,2.325581,3.631171
2,202,0.027472,2.747178,6.378349
3,178,0.024208,2.420781,8.799130
4,147,0.019992,1.999184,10.798314
5,102,0.013872,1.387189,12.185503
6,153,0.020808,2.080783,14.266286
7,197,0.026792,2.679179,16.945464
8,127,0.017272,1.727186,18.672651
9,82,0.011152,1.115191,19.787842
10,157,0.021352,2.135183,21.923025
11,185,0.025160,2.515980,24.439004
12,90,0.012240,1.223990,25.662995
13,116,0.015776,1.577587,27.240582
14,172,0.023392,2.339181,29.579763
15,111,0.015096,1.509588,31.089351
16,148,0.020128,2.012784,33.102135
17,213,0.028968,2.896777,35.998912
18,130,0.017680,1.767986,37.766898
19,165,0.022440,2.243982,40.010880
20,141,0.019176,1.917585,41.928465
21,149,0.020264,2.026384,43.954848
22,206,0.028016,2.801578,46.756426
23,175,0.023800,2.379981,49.136407
24,123,0.016728,1.672787,50.809194
25,128,0.017408,1.740786,52.549980
26,144,0.019584,1.958384,54.508364
27,168,0.022848,2.284782,56.793146
28,109,0.014824,1.482388,58.275534
29,167,0.022712,2.271182,60.546716
30,95,0.012920,1.291990,61.838705
31,163,0.022168,2.216782,64.055488
32,150,0.020400,2.039984,66.095471
33,154,0.020944,2.094383,68.189854
34,130,0.017680,1.767986,69.957840
35,143,0.019448,1.944784,71.902625
36,187,0.025432,2.543180,74.445804
37,166,0.022576,2.257582,76.703386
38,139,0.018904,1.890385,78.593771
39,149,0.020264,2.026384,80.620155
40,108,0.014688,1.468788,82.088943
41,119,0.016184,1.618387,83.707330
42,183,0.024888,2.488780,86.196110
43,151,0.020536,2.053584,88.249694
44,114,0.015504,1.550388,89.800082
45,135,0.018360,1.835985,91.636067
46,191,0.025976,2.597579,94.233646
47,137,0.018632,1.863185,96.096831
48,129,0.017544,1.754386,97.851217
49,158,0.021488,2.148783,100.000000